$ANSIBLE_VAULT;1.1;AES256
36363462636633356161303139383337626632633734363532343735366362333766346636376135
6165386562656366343638303561323139336561346430320a343161666233633833333261363363
37653461643436326438623632343966353566303633613935636466333266303038343531303532
3335333463396433640a333561373131343436643933346463383033303930333265643337646432
66363334333233386430633637373562393530336232646230393933383433313237
